// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int32         `json:"id"`
	AuthorID  sql.NullInt32 `json:"author_id"`
	RfcID     sql.NullInt32 `json:"rfc_id"`
	CreatedAt time.Time     `json:"created_at"`
}

type Rfc struct {
	ID        int32         `json:"id"`
	AuthorID  sql.NullInt32 `json:"author_id"`
	Message   string        `json:"message"`
	CreatedAt time.Time     `json:"created_at"`
	Archived  bool          `json:"archived"`
}

type User struct {
	ID       int32  `json:"id"`
	Email    string `json:"email"`
	Username string `json:"username"`
	Hash     []byte `json:"hash"`
}
